export const APP_NAME = 'Kally Threading – Multi-Branch CRM';

/** Logo used on login and in app nav (sidebar/topbar). File: public/images/Kally-Logo (1).webp */
export const LOGO_URL = '/images/Kally-Logo%20(1).webp';

export const ROUTES = {
  login: '/login',
  forgotPassword: '/forgot-password',
  admin: {
    root: '/admin',
    overview: '/admin/overview',
    branch: '/admin/branch',
    createVendor: '/admin/create-vendor',
    branches: '/admin/branches',
    sales: '/admin/sales',
    salesDetails: '/admin/sales/details',
    memberships: '/admin/memberships',
    membershipDetail: (id: string) => `/admin/memberships/${id}`,
    customers: '/admin/customers',
    customerMemberships: (customerId: string) => `/admin/customers/${customerId}/memberships`,
    customerAppointments: (customerId: string) => `/admin/customers/${customerId}/appointments`,
    packages: '/admin/packages',
    search: '/admin/search',
    leads: '/admin/leads',
    leadDetail: (id: string) => `/admin/leads/${id}`,
    appointments: '/admin/appointments',
    settlements: '/admin/settlements',
    loyalty: '/admin/loyalty',
    settings: '/admin/settings',
    tickets: '/admin/tickets',
    ticketDetail: (id: string) => `/admin/tickets/${id}`,
    salesImages: '/admin/sales-images',
    profile: '/admin/profile',
  },
  vendor: {
    root: '/vendor',
    branches: '/vendor/branches',
    sales: '/vendor/sales',
    memberships: '/vendor/memberships',
    membershipDetail: (id: string) => `/vendor/memberships/${id}`,
    customers: '/vendor/customers',
    customerMemberships: (customerId: string) => `/vendor/customers/${customerId}/memberships`,
    customerAppointments: (customerId: string) => `/vendor/customers/${customerId}/appointments`,
    search: '/vendor/search',
    leads: '/vendor/leads',
    leadDetail: (id: string) => `/vendor/leads/${id}`,
    appointments: '/vendor/appointments',
    settlements: '/vendor/settlements',
    loyalty: '/vendor/loyalty',
    tickets: '/vendor/tickets',
    ticketDetail: (id: string) => `/vendor/tickets/${id}`,
    salesImages: '/vendor/sales-images',
    profile: '/vendor/profile',
  },
} as const;
